#!/usr/bin/env python
from gazebo_msgs.msg import ModelStates
import unittest
import rospy

class TestResubscribe(unittest.TestCase):
  '''
  Test that messages from gazebo_ros_api plugin continue to be delivered
  after a subscriber is shutdown then resubscribed to the same topic.

  Attempts to reproduce the issue described in
  https://github.com/ros-simulation/gazebo_ros_pkgs/issues/596,
  which occured in certain versions of gazebo_ros with gazebo8+
  '''
  def cb(self, msg):
      self.fresh = False

  def setUp(self):
      rospy.init_node('test_ros_api_resubscribe', anonymous=True)
      self.fresh = True

  def test_resubscribe(self):
      # Wait for gazebo api plugin to come online
      service = '/gazebo/set_model_state'
      try:
        rospy.wait_for_service(service, 5.0)
      except rospy.ROSException:
        self.fail('Timed out waiting for service {}'.format(service))

      # Subscribe and unsubscribe several times
      for i in range(3):
        sub = rospy.Subscriber('/gazebo/model_states', ModelStates, self.cb, queue_size=1)
        # reset fresh flag so we can notice when a message arrives
        self.fresh = True
        rospy.sleep(1.0)
        self.assertFalse(self.fresh)
        sub.unregister()

if __name__ == '__main__':
  import rostest
  import sys
  rostest.rosrun('gazebo_ros', 'test_resubscribe', TestResubscribe, sys.argv)
    
