#!/bin/sh
final="$@"

EXT=so
if [ $(uname) = "Darwin" ]; then
    EXT=dylib
fi

# add ros plugin if does not exist
if [ `expr "$final" : '.*libgazebo_ros_paths_plugin\.$EXT.*'` -eq 0 ]
then
    final="$final -g `catkin_find --first-only libgazebo_ros_paths_plugin.$EXT`"
fi

# Combine the commands
setup_path=$(pkg-config --variable=prefix gazebo)/share/gazebo/
. $setup_path/setup.sh && gzclient $final
