#!/usr/bin/env python
import os
import rospkg

models_paths = set()

# look for exported model directories in all packages which depend
# on gazebo_ros
r = rospkg.RosPack()
for pkg_name in r.get_depends_on('gazebo_ros'):
    m = r.get_manifest(pkg_name)
    for e in m.exports:
        if 'gazebo_model_path' in e.attrs:
            new_models_path = e.attrs['gazebo_model_path']

            # relative paths are expanded relative to package directory
            if not os.path.isabs(new_models_path):
                new_models_path = os.path.join(
                    r.get_path(pkg_name), new_models_path)
            models_paths.add(new_models_path)

# print the value for the GAZEBO_MODEL_PATH variable. this is sorted so that
# it has a deterministic ordering; otherwise ros packages don't really have
# an ordering. anyone have a better idea on how to do that?
print ':'.join(sorted(models_paths))


