---
std_msgs/Header header               # Standard metadata for higher-level stamped data types.
                                     # * header.stamp Simulation time when data was collected.
string[] model_names                 # list of models in the world
bool success                         # return true if get successful
