gazebo_msgs/EntityState state   # Entity state to set to.
                                # Be sure to fill all fields, values of zero have meaning.
---
bool success                    # Return true if setting state was successful.
