# Deprecated, kept for ROS 1 bridge.
# Use SetEntityState
gazebo_msgs/LinkState link_state
---
bool success                # return true if set wrench successful
string status_message       # comments if available
