# Deprecated, kept for ROS 1 bridge.
# Use SetEntityState
gazebo_msgs/ModelState model_state
---
bool success                  # return true if setting state successful
string status_message         # comments if available
